apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine
      command:
        - /bin/sh
        - -c
      args: ["cat"]
      tty: true
      stdin: true
